### ISSUE TITLE
updateLocation does not update href property

### ISSUE THREAD

**Issue by digitalcora** [pbeshai/serialize-query-params#11]
When using `updateLocation` or `updateInLocation`, the `href` property of the returned object is not updated with the new query params. This would otherwise be a good way to pass the new location into functions like `history.pushState` that require a URL string, but currently you have to stitch together (at least) the `pathname` and `search` on your own.

```js
var loc = {
  host: "localhost:4000",
​  hostname: "localhost",
​  href: "http://localhost:4000/test?param=0",
  origin: "http://localhost:4000",
​  pathname: "/test",
​  port: "4000",
​  protocol: "http:",
  search: "?param=0"
};

var newLoc = updateInLocation({ param: "1" }, loc);
// => { ..., search: "?param=1", href: "http://localhost:4000/test?param=0" }
```

**Comment by pbeshai** [comment]
I'm not sure if it can actually safely be updated. If the location is the same object as `window.location` then you'd be doing `window.location.href = newHref` which would redirect the browser.

**Comment by digitalcora** [comment]
The returned location is definitely not the same object as `window.location`, otherwise setting e.g. the new `search` property on it would already be causing a page navigation.

Looking at the code, it copies all properties of `window.location` onto a new object, so that makes sense. However it's creating an inconsistency where `search` is updated, but `href` is not.

**Comment by pbeshai** [comment]
Ok! feel free to make a PR, happy to merge
