### ISSUE TITLE
withDefaults does not work if the property does not exist in the encodedQuery

### ISSUE THREAD

**Issue by hector** [pbeshai/serialize-query-params#30]
Maybe in `decodingQueryParams` you should iterate over the `paramConfigMap` and not the `encodedQuery`?

https://github.com/pbeshai/serialize-query-params/blob/407417676e806a9682a2373173f1fde17382adb4/src/decodeQueryParams.ts#L17

**Comment by pbeshai** [comment]
Fixed in v1.2.2, thank you!

**Comment by hector** [comment]
awesome, thanks!
