### ISSUE TITLE
createEnumParam with withDefault gives null in types

### ISSUE THREAD

**Issue by stianjensen** [pbeshai/serialize-query-params#39]
Using the following setup, I get a typescript error saying my enum param can still be null. Am I misunderstanding something, or should the types reflect that this value is never null?

```
const SortOrderEnumParam = createEnumParam(['asc', 'desc']);
const [filters, setFilters] = useQueryParams({
    sortBy: withDefault(SortOrderEnumParam, 'asc'),
});

const sorted = sortFunctions[filters.sortBy](unsorted);
```
> [tsserver 2538] [E] Type 'null' cannot be used as an index type
> [tsserver 2538] [E] Type 'undefined' cannot be used as an index type.

Revealing the types of other query params that use `withDefault` show that they are never null or undefined, but the ones using my custom enum param may still be both, according to typescript.

To please the typechecker, I have to add the default a second time, for instance like this:
```
const sorted = sortFunctions[filters.sortBy ?? 'asc'](unsorted);
```

**Comment by pbeshai** [comment]
Hi there, can you check out the response in this issue and see if it works for you? https://github.com/pbeshai/use-query-params/issues/141#issuecomment-769895181

**Comment by stianjensen** [comment]
Thanks for a super-quick response! 🎉 

Yeah - simply adding "as const" with no other changes was all that was needed. So the following type checks as I expected:

```
const SortOrderEnumParam = createEnumParam(['asc', 'desc']);
const [filters, setFilters] = useQueryParams({
    sortBy: withDefault(SortOrderEnumParam, 'asc' as const),
});

const sorted = sortFunctions[filters.sortBy](unsorted);
```

**Comment by pbeshai** [comment]
Great, glad that worked. Would be nice not to need to do that, but not sure how.
