### ISSUE TITLE
Update query-string dependency to v 6.8.3

### ISSUE THREAD

**Issue by fivethreeo** [pbeshai/serialize-query-params#4]
Api has not changed too much, should be trivial :)

**Comment by pbeshai** [comment]
There is an issue with this in that it dropped support from some browsers between 5 and 6, so I had to downgrade to 5 at some point. See https://github.com/pbeshai/use-query-params/issues/15 - 6 doesn't support IE11. Perhaps there's a way to make it so you can bring your own query-string...
