### ISSUE TITLE
Question: Why do empty array is returned empty string in encodeDelimitedArray?

### ISSUE THREAD

**Issue by akshitkrnagpal** [pbeshai/serialize-query-params#40]
Why do empty array is returned empty string in encodeDelimitedArray? Wouldn't it make more sense for it to return undefined so `/?foo=` is removed from the url?

> Assuming, `foo` is  CommaArrayParam (as defined in the example). 

When I remove all items from the array, it leaves an empty string, so `/?foo=` will be left in the URL. 

Just a curious question. Keep up the good work. 😄 

I am currently using custom param like this - 
https://gist.github.com/akshitkrnagpal/2baf5b7d41751bfcdc98f2d380bec3b0

**Comment by pbeshai** [comment]
This is because for any given parameter, we need to support:

```
?        // the param is undefined
?foo     // the param is null
?foo=    // the param is "empty"
?foo=val // the param has a value
```

Some people prefer having a distinction between an empty array and a null or undefined value, so the library leaves it up to you to decide. Your gist approach seems fine to me 👍
