### ISSUE TITLE
Delimited array params break when storing strings with '_' characters

### ISSUE THREAD

**Issue by dphilipson** [pbeshai/serialize-query-params#9]
Hi there! I absolutely love your work here and in `use-query-params`.

When using `DelimitedArrayParam`, since `_` is used as the delimiter, strings containing underscores are deserialized incorrectly (they are split into multiple strings after serialization then deserialization). To avoid this, some kind of escaping is necessary.

The same applies for strings with `-` or `_` characters when using `ObjectParam`s.

**Comment by pbeshai** [comment]
That's true, it's not very every use-case. The point of the default is to avoid any escaping if your strings do not have underscores. You could use ArrayParam or you can create your own delimiter that works for you:

Here is what the default implementation is:
```
export const DelimitedArrayParam: QueryParamConfig<
  string[] | null | undefined,
  string[] | undefined
> = {
  encode: Serialize.encodeDelimitedArray,
  decode: Serialize.decodeDelimitedArray,
};
```

Yours could be:

```
const CommaArrayParam = {
  encode: (array: string[] | null | undefined): string | undefined => 
    encodeDelimitedArray(array, ','),

  decode: (arrayStr: string | string[] | null | undefined): string[] | undefined => 
    decodeDelimitedArray(arrayStr, ',')
};
```

Note this is shown in the README under "Example with Custom Param"

**Comment by chrisvanpatten** [comment]
It would be great if you could just opt-in to query string bracket syntax, which avoids a lot of the pitfalls and limitations here. `query-string` supports it already with the `arrayFormat` [option](https://github.com/sindresorhus/query-string#stringifyobject-options).

**Comment by pbeshai** [comment]
You can just use `ArrayParam` unless I'm misinterpreting you? 

ArrayParam converts `foo = ['a_b', 'c_d']` to `foo=a_b&foo=c_d`

DelimitedArrayParam is just a more concise format when you know your data won't have characters that break it
